document.addEventListener("DOMContentLoaded", () => {
    const messageElement = document.getElementById("message");
    messageElement.textContent = "This message is generated by JavaScript!";

    console.log("Question 1. OneToTen:");
    oneToTen();

    console.log("Question 2. tenToOne:");
    tenToOne();

    console.log("Question 3. printInOrder:");
    const mySmallArray = [1,2,3,4,5,6,7,8,9,0];
    printInOrder(mySmallArray);

});
